### ISSUE TITLE
NODE declaration causes "out of index" errors

### ISSUE THREAD

**Issue by ryu-bu** [CIDARLAB/mint#12]
`NODE something`

causes the following error on fluigicad.org

```
Traceback (most recent call last):
  File "//.pyenv/versions/3.8.0/bin/fluigi", line 8, in <module>
    sys.exit(main())
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/fluigi/cmdline.py", line 165, in main
    size_nodes(current_device)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/fluigi/pnr/utils.py", line 11, in size_nodes
    gedge = list(nbers)[0]
IndexError: list index out of range
```

MINT file:
```
DEVICE device

LAYER FLOW
PORT p1, p2, p3, p4, p5, p6 r=700;
PORT c1, c2, c3, c4 r=700;
PORT pw1, pw2, pw3, pw4 r=700;
PORT cw1, cw2, cw3, cw4 r=700;
PORT something r=700;
PORT n1, n2, n3 r=700;

NODE something;

METER m1, m3, m4, m5, m6, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19 rotation=270 valveRadius=810 valveGap=395 flowChannelWidth=600 length=10710 width=11140;
METER m2 rotation=180 valveRadius=810 valveGap=395 flowChannelWidth=600 length=10710 width=11140;
MIXER mix1 rotation=90 channelWidth=600;
INCUBATOR inc1 rotation=90;
PUMP pu1, pu2, pu3, pu4, pu5 rotation=90 width=1200 flowChannelWidth=600;

CHANNEL ch1 from c1 to m1 1 w=600;
CHANNEL ch2 from p1 to pu1 1 w=600;
CHANNEL ch3 from pu1 2 to m1 2 w=600;
CHANNEL ch4 from m1 3 to cw1 w=600;
CHANNEL ch5 from m1 4 to pw1 w=600;
CHANNEL ch6 from m1 5 to mix1 1 w=600;

CHANNEL ch7 from p2 to pu2 1 w=600;
CHANNEL ch8 from pu2 2 to inc1 1 w=600;
CHANNEL ch9 from inc1 2 to mix1 1 w=600;

CHANNEL ch10 from mix1 2 to n1 w=600;
CHANNEL ch11 from p3 to n1 w=600;

CHANNEL ch12 from c2 to m2 1 w=600;
CHANNEL ch13 from p4 to pu3 1 w=600;
CHANNEL ch14 from pu3 2 to m2 2 w=600;
CHANNEL ch15 from m2 3 to cw2 w=600;
CHANNEL ch16 from m2 4 to pw2 w=600;
CHANNEL ch17 from m2 5 to n1 w=600;

CHANNEL ch18 from n1 to pu3 1 w=600;
END LAYER
```

**Comment by rkrishnasanka** [comment]
@ryu-bu can you give the full MINT file ? I can't run it with just this

**Comment by ryu-bu** [comment]
updated

**Comment by watturkara** [comment]
I actually think it is the pump declaration that causes this.
